#
//  .travis.yml
//  AnimationApp
//
//  Created by Анна Яцун on 17.01.2025.
//

language: swift
os: osx
osx_image: xcode14.2
xcode_project: YourProject.xcodeproj
xcode_scheme: YourSchemeName
xcode_destination: platform=iOS Simulator,OS=16.4,name=iPhone 14

before_install:
  - brew update
  - brew install swiftlint || true

script:
  - xcodebuild clean build test -project YourProject.xcodeproj -scheme YourSchemeName -destination "platform=iOS Simulator,OS=16.4,name=iPhone 14" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
